package org.clibankinjava.components.businessparts.businessentities.typeofbankpersonnel.duties;

public enum AssetManagerPrimaryDuties {

    RUNNING_AND_ANALYSING_INVENTORIES_OF_ALL_ASSETS,

    LIAISING_WITH_SUPPLIERS_TO_OBTAIN_THE_BEST_PRICE_FOR_ASSETS,

    INVESTING_MONEY_FOR_UPCOMING_PROJECTS,

    WORKING_WITH_ASSET_MANAGEMENT_SYSTEMS_AND_TRACKING_TECHNOLOGIES,

    ENSURING_FINANCIAL_RECORDS_ARE_UP_TO_DATE_AND_ACCURATE,

    MONITORING_MATERIALS_WORKFORCE_TOOLS_EQUIPMENT_AND_SUPPLIES,

    REPORTING_ON_FINANCE_AND_FORECASTING_BUDGETS,

    REVIEWING_CLIENT_FINANCIAL_PORTFOLIO,

    MONITORING_STOCK_MARKET,

    DETERMINE_BEST_INVEST_DECISION_FOR_CLIENT,

    INVEST_IN_STOCKS_AND_OTHER_ASSETS,

    MAKE_INFORMED_DECISIONS_POTENTIAL_INVESTMENTS

}
