package org.clibankinjava.components.businessparts.businessentities.typeofbankpersonnel.duties;

public enum BankerPrimaryDuties {
    SIGNING_NEW_CLIENTS,
    HELP_WITH_ONBOARDING_PROCESS,
    ADVISE_CUSTOMERS_ON_BANK_SERVICES,
    RESOLVE_ISSUES_WITH_BANKING_SERVICES_AND_ACCOUNTS,
    REFER_CLIENTS_TO_IN_HOUSE_FINANCIAL_EXPERTS,
    PRESENT_FINANCIAL_PRODUCTS_AND_SERVICES_TO_EXISTING_AND_PROSPECTIVE_CUSTOMERS,
    PERFORM_ADMINISTRATIVE_DUTIES,
    MEETINGS_WITH_BANK_MEMBERS,
    GIVING_HELP_ACQUIRING_LOANS,
    PAID_CONSULTATION
}
