package org.clibankinjava.components.businessparts.businessentities.typeofbankpersonnel.duties;

public enum BankTellerPrimaryDuties {

    CASH_CHECKS,

    WITHDRAW_MONEY,

    MOVE_TRANSACTIONS,

    CREATE_CHECKING_ACCOUNTS,

    CREATE_SAVINGS_ACCOUNTS,

    PROVIDE_CHECKS,

    INFORM_CLIENTS_OF_DIFFERENT_BANK_OFFERINGS,

    MAINTAINING_CONFIDENTIALITY_WITH_ALL_TRANSACTIONS,

    RECORDS_DAILY_TRANSACTIONS,

    COMPILE_WITH_BANK_SECRECY_ACT,

    ENSURE_QUALITY_SERVICES_TO_CUSTOMERS,

    ACCEPTING_DEPOSITS_AND_WITHDRAWALS,

    IDENTIFY_AND_RESOLVE_CUSTOMER_NEEDS,

    MAKE_SALES_REFERRALS,

    PROCESS_CASH_WITHDRAWALS,

    SERVES_CUSTOMERS_BY_COMPLETING_ACCOUNT_TRANSACTIONS,

    ANSWERING_CUSTOMER_QUESTIONS,
}
