package org.clibankinjava.components.businessparts.businessentities.typeofbankpersonnel.duties;

public enum CreditAnalystPrimaryDuties {
    REVIEWING_FINANCIAL_HISTORY,
    REVIEWING_CREDIT_SCORE,
    PROVIDE_RECOMMENDATION_FOR_APPROVING,
    GATHERS_AND_ANALYZES_LOAN_APPLICANTS_FINANCIAL_DATA_TO_EVALUATE_RISK,
    GATHERING_INFORMATION_ABOUT_CLIENTS,
    UNDERTAKING_RISK_ANALYSIS_BY_USING_SPECIALIST_SOFTWARE,
    DEVELOPING_STATISTICAL_MODELS,
    ASSESSING_FINANCIAL_INFORMATION,
    ANALYSING_FINANCIAL_INFORMATION,
    BUILDING_AND_MAINTAINING_CLIENT_RELATIONSHIPS,
    CREATING_AND_DELIVERING_PRESENTATIONS,
    CREATING_FINANCIAL_REPORTS,
    USING_CREDIT_SCORING_SYSTEMS_FOR_SMALL_CREDIT_AMOUNTS,
    HELPING_TO_ENHANCE_QUALITY_OF_CREDIT_APPLICATIONS
}
