package org.clibankinjava.components.businessparts.businessentities.typeofbankpersonnel.duties;

public enum FinancialAdvisorPrimaryDuties {
    HELP_CLIENTS_DETERMINE_GOALS,
    HELP_CLIENTS_TO_ACHIEVE_GOALS,
    TRADING_IN_THE_STOCK_MARKET,
    REVIEWING_FINANCIAL_HISTORY,
    PROVIDE_STRATEGIC_ADVICE_FOR_DEBT_MANAGEMENT,
    PROVIDE_ADVICE_FOR_CASH_MANAGEMENT,
    PROVIDE_STRATEGIC_ADVICE_FOR_DEBT_INSURANCE_COVERAGE,
    PROVIDE_ADVICE_FOR_INVESTMENTS,
    ASSESS_CLIENT_OVERALL_FINANCIAL_SITUATION,
    DEVELOP_FINANCIAL_PLAN,
    CULTIVATE_CLIENT_BASE_AND_BUILD_RELATIONSHIPS,
    GENERATE_LEADS,
    SELL_MUTUAL_FUNDS_STOCKS_AND_BONDS,
    OVERSEE_THE_COURSE_OF_THE_FINANCIAL_PLAN
}
