package org.clibankinjava.components.businessparts.businessentities.typeofbankpersonnel.duties;

public enum InternalAuditorPrimaryDuties {

    ASSESSING_COMPANY_FINANCIAL_RISK,

    SAFEGUARDING_ASSETS,

    GATHERING_AND_ANALYSING_DATA,

    CHECKING_THE_ACCURACY_OF_FINANCIAL_REPORTS,

    AUDITING_THE_EFFICIENCY_OF_BUSINESS_PROCESSES,

    ENSURING_THE_BUSINESS_ADHERES_TO_POLICIES_PROCEDURES_LEGISLATION_AND_REGULATIONS,

    STAKEHOLDER_COMMUNICATION,

    INVESTIGATE_FRAUD,

    DOCUMENT_THE_RESULTS_OF_AUDIT_PROCEDURES,

    ASSURE_SAFEGUARDS_ARE_IN_PLACE_TO_PROTECT_ORGANIZATION_S_RESOURCES
}
