package org.clibankinjava.components.businessparts.businessentities.typeofbankpersonnel.duties;

public enum InvestmentRepresentativePrimaryDuties {

    PROMOTE_INVESTMENT_PRODUCTS_AND_SERVICES,

    SELL_INVESTMENT_PRODUCTS_AND_SERVICES_TO_FINAL_CUSTOMERS,

    IDENTIFY_SALES_OPPORTUNITIES,

    GENERATE_SALES_OPPORTUNITIES,

    CROSS_SELL_ALL_INVESTMENT_PRODUCTS_AND_SERVICES,

    PARTICIPATE_IN_SALES_PROGRAM,

    MONITORING_THE_RENEWAL_OF_MATURING_INVESTMENTS,

    UPDATE_TRANSACTIONS_RECORDS,

    PROCESS_TRANSACTIONS_DOCUMENTS,

    COMPLETE_MUTUAL_FUND_LICENSING_REQUIREMENTS
}
