package org.clibankinjava.components.businessparts.businessentities.typeofbankpersonnel.duties;

public enum InvestmentBankerPrimaryDuties {

    CONDUCT_STRATEGIC_RESEARCH_AND_DUE_DILIGENCE_INVESTIGATIONS,

    ISSUE_DEBT_AND_SELL_EQUITY_TO_RAISE_CAPITAL,

    MANAGE_IPO_S_AND_PRIVATE_EQUITY_PLACEMENTS,

    DISCOVER_AND_CLOSE_POTENTIAL_INVESTORS,

    FACILITATE_MERGERS_AND_ACQUISITIONS,

    ASSIST_WITH_CORPORATE_RESTRUCTURING,

    ANALYZE_RISK_AND_OFFER_FINANCIAL_ADVICE,

    PREPARE_REPORTS_MODELS_AND_FORECASTS
}
