package org.clibankinjava.components.businessparts.businessentities.typeofbankpersonnel.duties;

public enum InvestmentBankingAnalystPrimaryDuties {

    MEETING_WITH_CLIENTS_OR_BANK_REPRESENTATIVES_TO_UNDERSTAND_FINANCIAL_NEEDS_AND_GOALS,

    SERVING_AS_AN_INTERMEDIARY_BETWEEN_INVESTORS_AND_CORPORATIONS_LOOKING_FOR_CAPITAL,

    USING_FINANCIAL_MODELS,

    DEVELOPING_NEW_FINANCIAL_MODELS,

    RESEARCHING_THE_HISTORICAL_AND_CURRENT_PERFORMANCE_OF_FINANCIAL_PRODUCTS,

    COLLECTING_AND_ANALYZING_FINANCIAL_DATA_TO_REVIEW_PORTFOLIOS_AND_OPPORTUNITIES,

    CREATING_NEW_FINANCIAL_OFFERINGS,

    COMPILING_REPORTS_ON_PORTFOLIOS_TRANSACTIONS_AND_PROJECTIONS,

    PERFORMING_ADMINISTRATIVE_DUTIES_WHEN_NEEDED
}
