package org.clibankinjava.components.businessparts.businessentities.typeofbankpersonnel.duties;

public enum LoanOfficerPrimaryDuties {
    PROCESS_LOAN_APPLICATIONS,
    EVALUATE_CREDIT_WORTHINESS,
    INTERVIEW_APPLICANTS_TO_DETERMINE_FINANCIAL_ELIGIBILITY,
    SETTING_UP_DEBT_PAYMENT_PLANS,
    DETERMINE_ALL_APPLICABLE_RATIOS_AND_METRICS,
    COMMUNICATE_WITH_CLIENTS,
    JUSTIFY_DECISIONS_AND_REPORT_ON_THEM,
    COMPLETE_LOAN_CONTRACTS_AND_COUNSEL_CLIENTS_ON_POLICIES_AND_RESTRICTIONS,
    MAINTAIN_AND_UPDATE_ACCOUNT_RECORDS,
    ASSESS_CUSTOMER_NEEDS_AND_INTRODUCE_DIFFERENT_TYPES_OF_LOANS,
    DEVELOP_REFERRAL_NETWORKS
}
