package org.clibankinjava.components.businessparts.businessentities.typeofbankpersonnel.duties;

public enum LoanProcessorPrimaryDuties {

    RISK_ANALYSIS,

    REVIEW_LOAN_APPLICATIONS,

    APPROVE_APPLICANTS,

    DENY_APPLICANTS,

    INTERVIEW_APPLICANTS_AND_EVALUATE_THEM,

    FOLLOW_UP_WITH_CLIENTS,

    FINALIZE_LOAN_CONTRACTS_AND_KEEP_CLIENTS_INFORMED,

    CREATE_AND_RENEW_RECORDS,

    IDENTIFY_CUSTOMER_NEEDS,

    CULTIVATE_TRUSTWORTHY_REFERRAL_NETWORKS,

    FORGE_TRUST_RELATIONSHIPS,

    ENHANCE_CUSTOMER_DEDICATION
}
