package org.clibankinjava.components.businessparts.businessentities.typeofbankpersonnel.duties;

public enum MortgageConsultantPrimaryDuties {
    RESEARCHING_CURRENT_MORTGAGE_RATES_AND_PRODUCTS,
    DETERMINING_OPTIONS_THAT_FIT_CLIENT_NEEDS,
    COMMUNICATING_WITH_LENDERS_TO_FIND_LOANS_FOR_CLIENTS,
    EXPLAINING_DETAILS_ABOUT_LOANS_TO_CLIENTS,
    DESCRIBING_DIFFERENCES_BETWEEN_LOAN_OPTIONS,
    REQUESTING_NECESSARY_DOCUMENTS_FROM_CLIENTS,
    VERIFYING_ALL_DOCUMENTATION,
    MANAGING_LOAN_PROCESSING_AND_CLOSING_PROCEDURES
}
