package org.clibankinjava.components.businessparts.businessentities.typeofbankpersonnel.duties;

public enum RelationshipManagerPrimaryDuties {

    UNDERSTAND_CUSTOMER_NEEDS,

    CULTIVATE_PROFITABLE_RELATIONSHIPS_IN_CLIENT_COMPANIES,

    RESOLVE_CUSTOMER_COMPLAINTS,

    FORWARD_UPSELLING_AND_CROSS_SELLING_OPPORTUNITIES_TO_SALES_TEAM,

    PROMOTE_HIGH_QUALITY_SALES_AND_SUPPLY,

    PROMOTE_CUSTOMER_SERVICE_PROCESSES,

    AIM_TO_PRESERVE_CUSTOMERS,

    RENEW_CONTRACTS,

    GAIN_SOLID_KNOWLEDGE_OF_COMPETITORS
}
