package org.clibankinjava.components.businessparts.businessentities.typeofbankpersonnel.duties;

public enum UnderwriterPrimaryDuties {
    REVIEW_APPROVED_LOANS_TO_ENSURE_ALL_LEGAL_REGULATIONS_ARE_MET,
    MAKE_SURE_ALL_COMPANY_POLICIES_ARE_MET,
    RESEARCH_ALL_AREAS_OF_AN_APPLICANTS_FINANCIAL_BACKGROUND_AND_MAKE_SURE_ALL_OK,
    CHECK_EMPLOYMENT_HISTORY,
    REVIEW_CREDIT_REPORTS,
    REVIEW_ASSET_INFORMATION,
    CREATE_RISK_ASSESSMENT_REPORTS_FOR_EACH_APPLICANT,
    ANALYZE_FINANCIAL_INFORMATION,
    ADVISE_THE_COMPANY_TO_APPROVE_OR_NOT_THE_LOAN_BASED_ON_RISK,
    CREDIT_RISK_ASSESSMENT,
    PROOFREAD_FILES_BEFORE_THEY_ARE_SUBMITTED_FOR_APPROVAL
}
